### ISSUE TITLE
TimeUnits

### ISSUE THREAD

**Issue by mosemister** [EconToolBox/Economist#1]
In Java, there is a time unit class that has the object of ``toSeconds()``

Less magic numbers doing it the official way and less change of bugs

**Comment by ColonelKai** [comment]
I would still have to have an enum that has that unit's equivelent of hours, minutes etc wouldn't I? also this is only for knowing the second equivelent of a time unit, nothing else, so,  I don't see the need.

**Comment by mosemister** [comment]
The ``TimeUnit.HOURS.toSeconds()`` achieves the same as your enum for Hours, so I don't see the point of having yours when its built into Java.

**Comment by ColonelKai** [comment]
okay yeah that's  fair
