### ISSUE TITLE
Get datafolder from static 

### ISSUE THREAD

**Issue by mosemister** [EconToolBox/Economist#2]
Your current implementation currently allows the getting of the data folder from static. Im sure your aware you will need to get the whole plugin for things too (schedulers for example). 

It would be best to hold the whole plugin as static with a ``getPlugin()`` static method and then for the data folder. Getting the plugin and then getting the datafolder from that. 

https://github.com/EconToolBox/Economist/blob/af5f7a5b82d14f663bcd9394a11f1ea642fa937c/src/main/java/econtoolbox/economist/Economist.java#L28

**Comment by ColonelKai** [comment]
https://github.com/EconToolBox/Economist/commit/2000241ef27ddb4b9e7dad3bd66e7ce4d6973ce2
