### ISSUE TITLE
Magic is in the air

### ISSUE THREAD

**Issue by mosemister** [EconToolBox/Economist#3]
I thought i taught you better then to use magic values? 

https://github.com/EconToolBox/Economist/blob/af5f7a5b82d14f663bcd9394a11f1ea642fa937c/src/main/java/econtoolbox/economist/misc/Files.java#L4

**Comment by ColonelKai** [comment]
https://github.com/EconToolBox/Economist/commit/87a68f2e4c7dda6133b7e999592674467e75aa20
