### ISSUE TITLE
Patent defined file

### ISSUE THREAD

**Issue by mosemister** [EconToolBox/Economist#4]
We typically define the parent when using ``File``

If you were to put the data folder path in the first argument and the path from that in the second. It would define the data folder as the parent

https://github.com/EconToolBox/Economist/blob/af5f7a5b82d14f663bcd9394a11f1ea642fa937c/src/main/java/econtoolbox/economist/managers/AbstractManager.java#L12

**Comment by ColonelKai** [comment]
https://github.com/EconToolBox/Economist/commit/14c543c4988723c0e31d795ed725ff1053c58a80
